### PR TITLE
Add build.rs config to use rust backends.

### PR DESCRIPTION
**Pull request by mutexlox-signal**

### CODE REVIEW

**Comment by padenot** [comment]
Do you mind fixing the `if ...` statements? that looks like debug code you forgot to remove. Thanks for the patch in any case, looks good for merging except this issue.

**Comment by mutexlox-signal** [comment]
Sorry about the noise on this; I accidentally pushed what I intended for https://github.com/mozilla/cubeb-rs/pull/93 to this branch.

**Comment by mutexlox-signal** [comment]
Note that this is blocked on https://github.com/mozilla/cubeb-pulse-rs/pull/94 and https://github.com/mozilla/cubeb-coreaudio-rs/pull/236 being merged, cubeb's submodules for them updating accordingly, AND this PR updating the submodule of cubeb in cubeb-rs.

**Comment by mutexlox-signal** [comment]
The first few steps are done -- cubeb-pulse-rs and cubeb-coreaudio-rs have the necessary updates. Next up is https://github.com/mozilla/cubeb/pull/801, then an update to this PR to bump cubeb's pinned commit.

**Comment by mutexlox-signal** [comment]
hmm, this is silently failing to build on linux when pulse is available... working on that now.

**Comment by mutexlox-signal** [comment]
Should be good now. There's a slight gap in CI -- I don't believe libpulse-dev is installed for the CI environment, so any problems that occur when libpulse is present on linux will be missed by CI -- but it does now build and pass tests with pulse

**Comment by padenot** [comment]
I opened a PR to fix the CI, but this looks good, thanks for the patch and mentioning the issue.

**Pull request merged**
